#!/bin/sh

set -xe

# Build qpdf
if [ ! -e qpdf/qpdf/libqpdf/build/.libs/libqpdf.a ]; then
  (
    set -xe
    cd qpdf/qpdf
    ./autogen.sh
    ./configure
    make
  )
fi

# Build jpeg
if [ ! -e qpdf/libjpeg-turbo/libjpeg.a ]; then
  (
    set -xe
    cd qpdf/libjpeg-turbo
    cmake -G"Unix Makefiles"
    make
  )
fi

# Build zlib
if [ ! -e qpdf/zlib/libz.a ]; then
  (
    set -xe
    cd qpdf/zlib
    ./configure
    make
  )
fi


mkdir -p out

GOOS=linux GOARCH=amd64 go build \
  -ldflags '-extldflags "-static"' \
  -o out/pdftilecut-linux-amd64 *.go
